"""ajout du champ siret aux entreprises

Revision ID: 02dff9694c55
Revises: 8db1189521fa
Create Date: 2026-05-27 00:08:47.973323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02dff9694c55'
down_revision: Union[str, Sequence[str], None] = '8db1189521fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('siret', sa.String(length=14), nullable=True))
    op.create_index(op.f('ix_companies_siret'), 'companies', ['siret'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_siret'), table_name='companies')
    op.drop_column('companies', 'siret')
    # ### end Alembic commands ###
