"""ajout_des_index_spatiaux_aux_jobs_et_profils

Revision ID: 443875a74cfc
Revises: 271aa639371c
Create Date: 2026-05-19 23:03:59.416763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443875a74cfc'
down_revision: Union[str, Sequence[str], None] = '271aa639371c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_job_location'), 'jobs', ['job_location'], unique=False)
    op.create_index(op.f('ix_user_profiles_location'), 'user_profiles', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_location'), table_name='user_profiles')
    op.drop_index(op.f('ix_jobs_job_location'), table_name='jobs')
    # ### end Alembic commands ###
