"""ajouter_le_champ_cv_key_au_profil

Revision ID: 8db1189521fa
Revises: 443875a74cfc
Create Date: 2026-05-21 22:43:03.693379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db1189521fa'
down_revision: Union[str, Sequence[str], None] = '443875a74cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('cv_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'cv_key')
    # ### end Alembic commands ###
