"""Add soft delete and audit fields to users

Revision ID: e9ea1c94e7aa
Revises: cf560bc401dd
Create Date: 2026-07-08 14:02:35.371905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ea1c94e7aa'
down_revision: Union[str, Sequence[str], None] = 'cf560bc401dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    op.add_column('applications', sa.Column('celery_task_status', sa.String(length=50), nullable=True))
    op.add_column('applications', sa.Column('celery_task_result', sa.JSON(), nullable=True))
    op.add_column('applications', sa.Column('modified_by', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_applications_celery_task_id'), 'applications', ['celery_task_id'], unique=False)
    op.add_column('companies', sa.Column('modified_by', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('modified_by', sa.String(length=255), nullable=True))
    op.drop_index(op.f('idx_jobs_required_skills_gin'), table_name='jobs', postgresql_ops={'required_skills': 'jsonb_path_ops'}, postgresql_using='gin')
    op.add_column('user_profiles', sa.Column('modified_by', sa.String(length=255), nullable=True))
    op.drop_index(op.f('idx_profiles_skills_gin'), table_name='user_profiles', postgresql_ops={'skills': 'jsonb_path_ops'}, postgresql_using='gin')
    op.add_column('users', sa.Column('modified_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modified_by')
    op.create_index(op.f('idx_profiles_skills_gin'), 'user_profiles', ['skills'], unique=False, postgresql_ops={'skills': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_column('user_profiles', 'modified_by')
    op.create_index(op.f('idx_jobs_required_skills_gin'), 'jobs', ['required_skills'], unique=False, postgresql_ops={'required_skills': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_column('jobs', 'modified_by')
    op.drop_column('companies', 'modified_by')
    op.drop_index(op.f('ix_applications_celery_task_id'), table_name='applications')
    op.drop_column('applications', 'modified_by')
    op.drop_column('applications', 'celery_task_result')
    op.drop_column('applications', 'celery_task_status')
    op.drop_column('applications', 'celery_task_id')
    # ### end Alembic commands ###
